Add org-modern-custom-timestamp-format
minad/org-modern pull request #30
Opened 2022-03-24 04:53 UTC by vizs

Continuation of #29.  I tried to cleanup the docstring of the new option.  I believe I exhausted the 15 LOC since I had a merge patched in Emacs.  I mailed assign@gnu.org and I am currently waiting for their reply.

2022-03-24 11:09 UTC, minad commented on org-modern.el
> +(defcustom org-modern-custom-timestamp-format '("%Y-%m-%d" . "%H:%M")
Set this to nil by default.

2022-03-24 11:12 UTC, minad requested changes

2022-03-24 11:12 UTC, minad commented on org-modern.el
> +    (when org-display-custom-times
Check the variable org-modern-custom-time-format instead if it is nil.

2022-03-24 11:12 UTC, minad commented on org-modern.el
>             (0 (org-modern--timestamp)))
Instead call a separate function here for the custom time format. We will have org-modern--timestamp-default and org-modern--timestamp-custom.

2022-03-24 12:58 UTC, vizs commented on org-modern.el
> +(defcustom org-modern-custom-timestamp-format '("%Y-%m-%d" . "%H:%M")
Done

2022-03-24 13:03 UTC, minad commented on org-modern.el
> +(defun org-modern--timestamp-custom ()
Thanks! I hope the code can be simplified a bit.

2022-03-24 13:03 UTC, minad commented on org-modern.el
> +    (remove-text-properties (match-beginning 0) (match-end 0) '(display nil))
`remove-list-of-text-properties`

2022-03-24 13:04 UTC, minad commented on org-modern.el
> +     'display " ")
Remove. Make the space part of org-odern-custom-timestamp-format.

2022-03-24 13:04 UTC, minad commented on org-modern.el
> +     'display " ")
Remove.

2022-03-24 13:06 UTC, minad commented on org-modern.el
> +     'display (format-time-string (car org-modern-custom-timestamp-format) time))
Probably these two calls to put-text-property can be merged into one add-text-properties call.

2022-03-24 13:06 UTC, minad commented on org-modern.el
> +       'display (concat " " (format-time-string (cdr org-modern-custom-timestamp-format) time))))))
Same here. These calls can probably be merged too.

2022-03-24 13:08 UTC, minad commented
Please take your time to polish this a little bit. There is no hurry and we have to wait for the FSF assignment anyway.

2022-03-24 13:12 UTC, vizs commented on org-modern.el
> +    (remove-text-properties (match-beginning 0) (match-end 0) '(display nil))
Okay, I wasn't sure which function to prefer.

2022-03-24 13:13 UTC, vizs commented on org-modern.el
> +     'display " ")
Then I suppose I need to document this part i.e., that we need an explicit space at the end of date format?

2022-03-25 12:38 UTC, minad commented on org-modern.el
> +     'display " ")
Yes this should be documented. You can also give example configurations as part of the :type specification of the defcustom.

2022-04-05 23:04 UTC, minad commented
@vizs What is the status here?

2022-04-06 02:18 UTC, vizs commented
I'm currently in the middle of exam season but even if I manage to find the time to finish this up, we still have to wait for FSF to reply.  They haven't sent back me the form (it's been a month)... I mailed copyright-clerk@gnu.org two days before for a status update.

2022-04-06 03:29 UTC, minad commented
Okay please notify me!

2022-04-20 12:18 UTC, vizs commented
My copyright assignment is finished now.  I hope to get to the reviews on 29th or 30th Apr.  Thanks for your patience

2022-04-22 08:17 UTC, vizs commented
@minad Please check if everything is okay

2022-04-22 08:26 UTC, vizs commented
Oops, looks like there are some fallouts after the merge (I did not check the relevant hunk carefully!), I will get to it this evening.

2022-04-22 09:09 UTC, merged

2022-04-22 09:45 UTC, minad commented
Okay, I merged your PR. I went over it again and thought that we could compress things a little more by simply reusing the org-modern-timestamp variable also for custom formats, see https://github.com/minad/org-modern/commit/ff1046705b3950b7a49da50bc34c11da86c6226d. Please check if everything still works okay for you.