Allowing different representations to "hidestar" in org heading
minad/org-modern pull request #98
Opened 2022-10-14 14:23 UTC by Inc0n

This is a PR that addresses a feature request made by me (https://github.com/minad/org-modern/issues/96#issuecomment-1276395109).

The scope of this PR is to add support for org-modern-hidestar, to use either string or char to replace each leading org heading stars.

Please advise on further actions.

2022-10-14 14:32 UTC, minad commented on org-modern.el
>          ,@(and (not (eq org-modern-hide-stars t)) org-modern-star '((0 (org-modern--star))))
I'd prefer if you update org-modern--star to also handle the char replacement for the leading chars.

2022-10-14 14:32 UTC, minad commented on org-modern.el
> +          char
Add a description.

2022-10-14 14:39 UTC, minad requested changes
Thanks! Before we proceed, do you have assigned copyright to the FSF? See https://github.com/minad/org-modern#contributions.

2022-10-14 16:33 UTC, Inc0n commented
> Thanks! Before we proceed, do you have assigned copyright to the FSF? See https://github.com/minad/org-modern#contributions.

Hi, so I haven't been assigned. Would the instructions in this link https://www.fsf.org/licensing/assigning.html be the procedure I should be following? Would that mean I should expect a questionnaire from you (i.e. the maintaner??) 

Thanks in advance.

2022-10-14 16:42 UTC, minad commented
Follow the straightforward process described here: https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633. Please let me know when you completed the assignment.

2022-10-19 17:23 UTC, minad commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
We won't stick to the current solution. But we can still use a cache for the propertized string with face org-modern-symbol.

2022-10-19 17:24 UTC, minad commented on org-modern.el
> +        ,@(and (or (stringp org-modern-hide-stars) (characterp org-modern-hide-stars))
Yes, like this.

2022-10-19 17:24 UTC, minad commented
@Inc0n Great! Can you please make the requested changes?

2022-10-19 17:27 UTC, Inc0n commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
I have changed to setting individual stars as of now, I shall push that commit and let you have a look before instructing on how we should proceed with caching and faces or what not. 
How does that sound?

2022-10-19 17:28 UTC, Inc0n commented on org-modern.el
> +          char
How about something like:
>  "Changes the displays of the stars.
Can be leading, t, or a string replacement for each leading star.
Set to nil to disable."

2022-10-19 17:32 UTC, minad commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
Note that we need at least two different strings. Maybe you've seen this before - the display property is compared with eq.

~~~ elisp
(let ((x1 "x")
      (x2 "x"))
  (insert (concat
           (propertize "a" 'display x1)
           (propertize "b" 'display x2)
           (propertize "c" 'display x1)
           (propertize "c" 'display x2))))
~~~

> I have changed to setting individual stars as of now, I shall push that commit and let you have a look before instructing on how we should proceed with caching and faces or what not.
How does that sound?

No, please add some variable which caches the string since we also do that for the other elements. Maybe it is overkill but that's what I use for the other elements. On the other hand if the strings are reallocated on every fontification it may even lead to some savings on legacy systems. Also the cache variables make it easier for the user to make changes by overwriting the variables.

Anyway, let's not over discuss these things. It is a simple feature.

2022-10-19 17:42 UTC, Inc0n commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
I think I definitely get where your concerns are coming from, which in the latest commit (third one), I have used `compose-region` instead of "put display property". 
I also agree that this discussion is fairly lengthy, for a simple feature. So if you find `compose-region` may have similar concerns or any other issues, I will just work on cache and get it done.
Thanks in advance.

2022-10-19 17:52 UTC, minad commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
Look, `compose-region` is entirely the wrong approach. We intentionally don't use it. Please take a look at the README.

2022-10-19 18:56 UTC, Inc0n commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
Ok, so if I understood correctly of your suggestion, we wish to make a cache of perhaps just two copies of `org-modern-hide-stars` (which is a string of course). Then each individual stars will be replaced alternatively, which eliminate the string allocation otherwise. 

Did I miss anything about propertize with face org-symbol?

2022-10-19 22:52 UTC, minad commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
Exactly, the display property should be set two alternating to one or the other. The strings should be propertized with org-modern-symbol. See the existing star cache.

2022-10-19 23:10 UTC, Inc0n commented on org-modern.el
> +    (put-text-property beg end 'display acc)))
Right. Done. Please check the latest commit (4).

2022-10-20 07:51 UTC, minad commented
Merged with changes, see https://github.com/minad/org-modern/commit/59b2e3c94756b4e37b2cf7b9f81028c6d4758672.

2022-10-20 07:51 UTC, closed without merging